### ISSUE TITLE
Details about PM

### ISSUE THREAD

**Issue by AbhimanyuAryan** [appetizermonster/unity-packman#6]
Hi,

Is this the package manager that we are using in Unity 2018?

**Comment by appetizermonster** [comment]
I don't think so, I'm not involved in developing games using Unity for nowadays. but this repo isn't the official package manager for Unity 2018. Thanks!

**Comment by AbhimanyuAryan** [comment]
Do you know who's building official PM in Unity Team? @appetizermonster

**Comment by appetizermonster** [comment]
I don't have any information for that. Sorry.
